{{ Html::script('assets/Hoang_library/admin/js/jquery.js') }}
{{ Html::script('assets/Hoang_library/admin/js/jquery-1.8.3.min.js') }}
{{ Html::script('assets/Hoang_library/admin/js/bootstrap.min.js') }}
{{ Html::script('assets/Hoang_library/admin/js/jquery.dcjqaccordion.2.7.js') }}
{{ Html::script('assets/Hoang_library/admin/js/jquery.scrollTo.min.js') }}
{{ Html::script('assets/Hoang_library/admin/js/jquery.nicescroll.js') }}
{{ Html::script('assets/Hoang_library/admin/js/jquery.sparkline.js') }}
{{ Html::script('assets/Hoang_library/admin/js/common-scripts.js') }}
{{ Html::script('assets/Hoang_library/admin/js/gritter/js/jquery.gritter.js') }}
{{ Html::script('assets/Hoang_library/admin/js/gritter-conf.js') }}
{{ Html::script('assets/Hoang_library/admin/js/sparkline-chart.js') }}
{{ Html::script('assets/Hoang_library/admin/js/zabuto_calendar.js') }}    
